print("my daily routine")
print("i wake up")
print("i eat")
print("i go to school at 7:40 AM")
print("i eat in school lucnh")
print("i play SOMETIMES! with my friends")
print("i eat")
print("i eat again")
print("i eat snacks")
print("i drink water or other liquid")
print("i go to get berries SOMETIMES")
print("i study")
print("i go watch tv or device")
print("i eat")
print("i eat")
print("i go to bed but not sleep")
print("i stare at celling")
print("i create a new drama in my head VERY DRAMATIC or just do crafts at night")
print("i sleep probably 2-4 hours later")